<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
        <PackageReference Include="MSTest" Version="4.3.3" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
        <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VioletManager.Application\VioletManager.Application.csproj" />
        <ProjectReference Include="..\VioletManager.Domain\VioletManager.Domain.csproj" />
    </ItemGroup>

</Project>
